name: file_system_access_api
description: A Dart library to expose the File System Access Api from web platform.
version: 2.0.0
homepage: https://github.com/poirierlouis/file_system_access_api/

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  universal_html: ^2.2.4
  js: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.4
  build_web_compilers: ^4.0.7
  lints: ^4.0.0
